// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package contacts

import ()

type Contact struct {
	ID       int64
	Fname    string
	Lname    string
	Phone    string
	Email    string
	Birthday string
	Address  string
	City     string
	State    string
	Zipcode  string
	Notes    string
}
